As Christmas approaches, Adam decides that he wants to improve his network security. 
He is inspired by the nearly identical Christmas Trees in his office with the only difference 
being the number on the star on top, and writes a hash function to generate a key.
 His instructions are found here:
 https://mega.nz/#!vawiwIBL!MNh3kyh12f_V8xtpHVCiBz5svr7Npvdhu6uzUkS08Tg - 
 The trees in Adam's office can be found here (your input):
 https://mega.nz/#!PGw2SCDZ!yzI2DCX0ut-TR5WBDX2x_aqtNQezg9WTGcxcmHlNJNs - 
 What is the encryption key generated by Adam's Christmas Tree Hash function?As Christmas approaches, 
 Adam decides that he wants to improve his network security. 
 He is inspired by the nearly identical Christmas Trees in his office with the only difference being the number on the star on top,
 and writes a hash function to generate a key. His instructions are found here:
 https://mega.nz/#!vawiwIBL!MNh3kyh12f_V8xtpHVCiBz5svr7Npvdhu6uzUkS08Tg - 
 The trees in Adam's office can be found here (your input):
 https://mega.nz/#!PGw2SCDZ!yzI2DCX0ut-TR5WBDX2x_aqtNQezg9WTGcxcmHlNJNs - 
 What is the encryption key generated by Adam's Christmas Tree Hash function?
 
 
 Pierdoloneprawojazdy123!